{% set version = "0.2.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppcnpy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppCNPy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppCNPy/RcppCNPy_{{ version }}.tar.gz
  sha256: 856dbc857b2d425c80d9a1628e45743234fee2e68575aa9e2d29a6efae60c39a

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('RcppCNPy')"           # [not win]
    - "\"%R%\" -e \"library('RcppCNPy')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/rcpp.cnpy.html
  license: GPL-2.0-or-later
  summary: The 'cnpy' library written by Carl Rogers provides read and write facilities for files created with (or for) the 'NumPy' extension for 'Python'. Vectors and matrices of numeric types can be read or written to and from files as well as compressed files. Support for integer files is available if the package has
    been built with -std=c++11 which should be the default on all platforms since the release of R 3.3.0.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - marcelmat12
