appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dGC3oVSQzpoCzQnIScLC2la5dw1EBJFEo5Lt9Yuw9+5wG/dO3XoTYKTsWF4R0h4i2cE7fz2tIkrBEntvq5Q5irIn29Y1c7o3KQuOta2UV6yBdXzzNVJEhuXhmhoNy4u82Ubd4Eyy0nx/+cLW4/E9BHCMcCcUjVF2AcBmlBIJUCxff+vYMiznu8nm2WG2vyaPUE1Zs6v+aHyHYo9lI0Guw/3xIgvIYEhvidWyXpeN13cTPw7TvgSfXLd9qeMhQ9Eml/+E8aHb8Qo7bcrUm6q4ysmyGY8d5tbVsp019IVzgdApasB26ig6gYQxVYaXNNXxGZYigOuet/41125y8/sU2iuDu3AScJMFxPhEFgsHe+Qwkl2yzF8biS8uan8Z9XtU34nJeJ7KGgMkMaiCXXzf7n6oBNRHS0LXzgD9dbApXsrIQr8yeU6vFZRHXaZooIaeRMYutvuak4icDzzXSmPTSO/CksNX2VKIZlwA6L4vHe/5VNMzaoaWFXVBDZji26yiYxNEjLZII6QJkrcoI4LyNcs97Bs+MYjxCf88pi+Z5nnEwLV+92hqF7ICse66JdL/dFfBxXV/CCUscSA0RHs9H32bMuLmiFMZi0PBpMEoHEAqKOZYBhANU6bH/Y/1YXtrg0r8WMJoETgqYAGnX0VfIZsBs/eYfMPj6Y00vFk2aSE=}
