travis:
  secure:
    BINSTAR_TOKEN: JJfHo6V1l+RpMqCfURWFfM6mDeOM4BqUK5nh5J+pJNdM0Yz5YrO8p5Fa3TfhRH+wNeOuOv3ZORN650Ym/ZbZ2/SFY45IkQaMhJtV2H+B7/CWN3XhaXft4iqwBj4bjQJ8tGiFDf1mdp2nxfTzAsqVsa2kyD91ocHp0/HWWGAW1oFycyXfwFms2qh080rYaE2ZmAXtJcKaSdLAm3WzD3kee35Z7QIq+RQVC2WzNjk1s0cdZ9BVOIuGwJOqTYrY7m8djEqjsHDVkjKYMZUo388pCQnkyVCvUP6Vm3ljnERVHkmm8A3hhOxMWIK3biTauVfP2dTxeGHgLC8UHiEOwOccPCtmFTqI2P/7NbqMPpOCwoV2UluIhFjE0RiqNx0vy5DeM90Hw5ikMIzC6djJUCgQRyNNXXvONuMmNx8j8S542fBKCiiHHYXz1l8PB0gixVPnZFV9u7ww+5ObDkP/+p07KZsD4snrQxdcd1qt8FU3C4TqHatuRtmGrKv7T43m1KVkQ4e4cN5QEsRjuKl11u39YUTM6umYeXSmLk882Jus3auH3mFj/hdracJg9b2E0ikoPpvaPopE0MHV/pkZ2QwaRl/d+vPFCLwFFtytGat69OiZKDyO0gBHD8VlFLyAsWly/yYJyoCfiJPbw71JUfX2pk7tB6zaRx+94HSpExoJ8ZE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
